# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#

default: &default
  adapter: postgresql
  encoding: utf8
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: kowalski_development
  username: bruno
  password: mesa3rosa

development:
  <<: *default

  # The above config should "just work" on Mac with PostgreSQL
  # installed via Homebrew. If it doesn't work for you, try the
  # UNIX domain socket or TCP socket methods as shown here:

  # Connect via domain socket in /tmp (some installs use /var/run/postgresql)
  # host: /tmp
  # username: <%= ENV["USER"] %>
  # password:

  # Connect on a TCP socket.
  # host: localhost
  # port: 5432
  # username: my_postgres_user
  # password: my_postgres_password

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: kowalski_test
